apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy
  name: busy
spec:
  containers:
  - image: busybox
    name: busy
    command: ["sleep", "infinity"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
