apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "update nginx to 1.27.4-perl"
  labels:
    app: app-nginx
  name: app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - image: nginx:1.27.4-perl
        name: nginx
        resources: {}
status: {}
