apiVersion: v1
data:
  vhost.conf: "# à placer dans /etc/nginx/conf.d/vhost.conf\r\nserver {\r\n    index
    index.php index.html;\r\n    # ip de la vm\r\n    server_name localhost;\r\n    error_log
    \ /var/log/nginx/error.log;\r\n    access_log /var/log/nginx/access.log;\r\n    root
    /usr/share/nginx/html;\r\n\r\n    location ~ \\.php$ {\r\n        # ip du conteneur
    php\r\n        fastcgi_pass    127.0.0.1:9000;\r\n        fastcgi_index   index.php;\r\n
    \       include         fastcgi_params;\r\n        fastcgi_param   SCRIPT_FILENAME
    \   /srv$fastcgi_script_name;\r\n        fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;\r\n
    \   }\r\n}\r\n"
kind: ConfigMap
metadata:
  name: nginx-vhost
